




const AllGames = [
    {//1
        id:"00W" ,
        name:"World Of Warcraft" ,
        company:'Blizzard Entertainment',
        type:"3D",
        platforms:["Windows" ] ,
        stock:80 ,
        genres:["Strategy","Multiplayers"] ,
        image : '../FakeData/MainImages/WordOfWarcraft.jpg',
        price:1.60,
        like:true ,
    },
    {//2
        id:"01V" ,
        name:"Valorant" ,
        company:'Riot Games',
        type:"3D",
        platforms:["Windows" , "MacOs"] ,
        stock:40 ,
        genres:["Action","Shooting","Survival"] ,
        image : '../FakeData/MainImages/Valorant.jpg',
        price:3.5,
        like:false ,
    },
    {//3
        id:"02T" ,
        name:"Tic Toc Toe" ,
        company:'Unknow',
        type:"2D",
        platforms:["Windows" , "MacOs"] ,
        stock:67 ,
        genres:["Board","Puzzle"] ,
        image : '../FakeData/MainImages/TicTocToe.jpg',
        price:0,
        like:false ,
    },
    {//4
        id:"03T" ,
        name:"Tetris" ,
        company:'Unknow',
        type:"2D",
        platforms:["Windows" , "MacOs","Android"] ,
        stock:90 ,
        genres:["Puzzle"] ,
        image : '../FakeData/MainImages/Tetris.jpg',
        price:0.5,
        like:true ,
    },
    {//5
        id:"04A" ,
        name:"Angry Birds" ,
        company:'Rovio Entertainment',
        type:"2D",
        platforms:["Windows" , "MacOs" , "Android"] ,
        stock:79 ,
        genres:["Puzzle" , "Strategy"] ,
        image : '../FakeData/MainImages/AngryBirds.jpg',
        price:2.1,
        like:true ,
    },
    {//6
        id:"05A" ,
        name:"Angry Birds Go" ,
        company:'Rovio Entertainment',
        type:"3D",
        platforms:["Windows"  ] ,
        stock:14 ,
        genres:["Racing" , "Sports"] ,
        image : '../FakeData/MainImages/AngryBirdsGo.jpg',
        price:4.33,
        like:true ,
    },
    {//7
        id:"06A" ,
        name:"Angry Birds Rio" ,
        company:'Rovio Entertainment',
        type:"2D",
        platforms:["Windows" ,"MacOs" , "Android" ,"Linux" ] ,
        stock:26 ,
        genres:["Puzzle" , "Stratege"] ,
        image : '../FakeData/MainImages/AngryBirdsRio.jpg',
        price:0.99,
        like:false ,
    },
    {//8
        id:"07A" ,
        name:"Angry Birds Space" ,
        company:'Rovio Entertainment',
        type:"2D",
        platforms:["Windows" ,"MacOs" , "Android" ,"Linux" ] ,
        stock:59 ,
        genres:["Puzzle" , "Stratege"] ,
        image : '../FakeData/MainImages/AngryBirdsSpace.jpg',
        price:1.99,
        like:false ,
    },
    {//9
        id:"08T" ,
        name:"Taken" ,
        company:'Bandai Namco Studios',
        type:"2D",
        platforms:[ "PS" ] ,
        stock:41 ,
        genres:["Fighting" , "Action"] ,
        image : '../FakeData/MainImages/Taken.jpg',
        price:2.24,
        like:false ,
    },
    {//10
        id:"09T" ,
        name:"Tag" ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" ] ,
        stock:32 ,
        genres:["Puzzle" , "Survival"] ,
        image : '../FakeData/MainImages/Tag.jpg',
        price:0,
        like:false ,
    },
    {//11
        id:"10S" ,
        name:"Super Mario" ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" ] ,
        stock:8 ,
        genres:["Puzzle" , "Survival"] ,
        image : '../FakeData/MainImages/SuperMario.jpg',
        price:7.25,
        like:true ,
    },

    {//12
        id:"11S" ,
        name:"Stranghold Legend" ,
        company:'Firefly Studios',
        type:"3D",
        platforms:[ "Windows" ] ,
        stock:97 ,
        genres:["Strategy" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/StrangholdLegends.jpg',
        price:12,
        like:true ,
    },
    {//13
        id:"12A" ,
        name:"Angry Birds Star Wars" ,
        company:'Rovio Entertainment',
        type:"2D",
        platforms:[ "Windows" , "MacOs" , "Android" ] ,
        stock:77 ,
        genres:["Puzzle" , "Straregy"] ,
        image : '../FakeData/MainImages/AngryBirdsStarWars.jpg',
        price:3,
        like:true ,
    },
    {//14
        id:"13A" ,
        name:"Apex Legend" ,
        company:'Respawn Entertainment',
        type:"3D",
        platforms:[ "Windows"  , "Linux" , "Xbox"] ,
        stock:97 ,
        genres:["Fighting" , "Shooting" , "Action" ,"Battrlroyal" ,"Multiplayer", "Survival"] ,
        image : '../FakeData/MainImages/ApexLegends.jpg',
        price:15,
        like:true ,
    },
    {//15
        id:"14A" ,
        name:"Asterix And Obelix In Olymic Games" ,
        company:'Unknow',
        type:"3D",
        platforms:[ "Windows"  , "Ps" , "Xbox"] ,
        stock:100 ,
        genres:["Fighting"  , "Action" ,"Multiplayer" , "Adventure"] ,
        image : '../FakeData/MainImages/AsterixAndObelixInOlympicGames.jpg',
        price:20,
        like:false ,
    },
    {//16
        id:"15A" ,
        name:"Asterix And Obelix XXI" ,
        company:'Unknow',
        type:"3D",
        platforms:[ "Windows"  , "Ps" , "Xbox"] ,
        stock:74 ,
        genres:["Fighting"  , "Action" ,"Multiplayer" , "Adventure"] ,
        image : '../FakeData/MainImages/AsterixAndObelixXxl.jpg',
        price:18,
        like:false ,
    },
    {//17
        id:"16S" ,
        name:"Stranghold Crusader" ,
        company:'Firefly Studios',
        type:"3D",
        platforms:[ "Windows"  , ] ,
        stock:44 ,
        genres:[  "Multiplayer" ,"Strategy" , "Survival"] ,
        image : '../FakeData/MainImages/StrangholdCrusader.jpg',
        price:32.4,
        like:true ,
    },
    {//18
        id:"17S" ,
        name:"Stranghold Capture 2 " ,
        company:'Firefly Studios',
        type:"3D",
        platforms:[ "Windows" ] ,
        stock:78 ,
        genres:[  "Multiplayer" ,"Strategy" , "Survival"] ,
        image : '../FakeData/MainImages/StrangholdCpture2.jpg',
        price:21.7,
        like:false ,
    },
    {//19
        id:"18S" ,
        name:"Snake " ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" , "MacOs" , "Linux" , "Android" ] ,
        stock:52 ,
        genres:[  "Multiplayer" ,  "Survival"] ,
        image : '../FakeData/MainImages/Snake.jpg',
        price:14,
        like:false ,
    },
    {//20
        id:"19S" ,
        name:"Sikman " ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" , "MacOs"  , "Android" ] ,
        stock:91 ,
        genres:[ "Survival" , "Fighting" ] ,
        image : '../FakeData/MainImages/SikMan.jpg',
        price:0.66,
        like:false ,
    },
    {//21
        id:"20B" ,
        name:"Bad pigs " ,
        company:'Rovio Entertainment',
        type:"2D",
        platforms:[ "Windows" , "MacOs" , "Linux" , "Android" ] ,
        stock:20 ,
        genres:["Puzzle"] ,
        image : '../FakeData/MainImages/BadPigs.jpg',
        price:5,
        like:true ,
    },
    {//22
        id:"21B" ,
        name:"Battlefield 2042 " ,
        company:'DICE',
        type:"3D",
        platforms:[ "Windows" , "Linux"  ] ,
        stock:30 ,
        genres:[ "Shooting" , "Action" ,"Survival" , "Multiplayer" , "Adventure"] ,
        image : '../FakeData/MainImages/Battlefield2042.jpg',
        price:78,
        like:false ,
    },
    {//23
        id:"22C" ,
        name:"Chess " ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" ,"MacOs" ,  "Linux"  ] ,
        stock:40 ,
        genres:[ "Puzzle" ,"Board" , "Sports" , "Strategy"] ,
        image : '../FakeData/MainImages/Chess.jpg',
        price:40,
        like:true ,
    },
    {//24
        id:"23C" ,
        name:"Circle Empire " ,
        company:'Luminous Games',
        type:"2D",
        platforms:[ "Windows" , "Linux"  ] ,
        stock:19 ,
        genres:[ "Survival" , "Multiplayer" , "Strategy"] ,
        image : '../FakeData/MainImages/CircleEmpire.jpg',
        price:7.8,
        like:false ,
    },
    {//25
        id:"24S" ,
        name:"Shrek " ,
        company:'Unknow',
        type:"3D",
        platforms:[ "Windows"  ] ,
        stock:4 ,
        genres:[ "Multiplayer" , "Adventure"] ,
        image : '../FakeData/MainImages/Shrek.jpg',
        price:10,
        like:false ,
    },
    {//26
        id:"25R" ,
        name:"Resident Evil 3  " ,
        company:'Capcom',
        type:"3D",
        platforms:[ "Windows" , "Linux" ] ,
        stock:80 ,
        genres:[ "Multiplayer" , "Horror" , "Action"] ,
        image : '../FakeData/MainImages/ResidentEvil3.jpg',
        price:50,
        like:true ,
    },
    {//27
        id:"26R" ,
        name:"Resident Evil 2" ,
        company:'Capcom',
        type:"3D",
        platforms:[ "Windows" , "Linux" ] ,
        stock:71 ,
        genres:[ "Multiplayer" , "Horror" , "Action"] ,
        image : '../FakeData/MainImages/ResidentEvil2.jpg',
        price:32.70,
        like:false ,
    },
    {//28
        id:"27R" ,
        name:"Resident Evil 1" ,
        company:'Capcom',
        type:"3D",
        platforms:[ "Windows" ] ,
        stock:10 ,
        genres:[ "Multiplayer" , "Horror" , "Action"] ,
        image : '../FakeData/MainImages/ResidentEvil1.jpg',
        price:18.99,
        like:false ,
    },
    {//29
        id:"28P" ,
        name:"Pubg" ,
        company:'PUBG Studios',
        type:"3D",
        platforms:[ "Windows" ] ,
        stock:60 ,
        genres:[ "Shooting" , "Battleroyal" , "Survival" ,"Racing"] ,
        image : '../FakeData/MainImages/Pubg.jpg',
        price:6.69,
        like:true ,
    },
    {//30
        id:"29P" ,
        name:"PlantVsZombies 2" ,
        company:'PopCap Games',
        type:"2D",
        platforms:[ "Windows" , "Linux" ,"MacOs" , "Android"] ,
        stock:60 ,
        genres:[ "Strategy" , "Survival" ,"Puzzle"] ,
        image : '../FakeData/MainImages/PlantVsZombies2.jpg',
        price:37,
        like:false ,
    },
    {//31
        id:"30P" ,
        name:"PlantVsZombies 1" ,
        company:'PopCap Games',
        type:"2D",
        platforms:[ "Windows" , "Linux" ,"MacOs" , "Android" ] ,
        stock:60 ,
        genres:[ "Strategy" , "Survival" ,"Puzzle"] ,
        image : '../FakeData/MainImages/PlantVsZombies1.jpg',
        price:21.77,
        like:true ,
    },
    {//32
        id:"31P" ,
        name:"PES 2022" ,
        company:'Konami',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:77 ,
        genres:[ "Sport"  , "Strategy" , "Multiplayer"] ,
        image : '../FakeData/MainImages/Pes2022.jpg',
        price:90,
        like:false ,
    },
    {//33
        id:"32C" ,
        name:"Call Of Duty Black Ops" ,
        company:'',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:300 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_BO.jpg',
        price:70,
        like:true ,
    },
    {//34
        id:"33C" ,
        name:"Call Of Duty Black Ops 2" ,
        company:'',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:470 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_BO2.jpg',
        price:88.99,
        like:false ,
    },
    {//35
        id:"34C" ,
        name:"Call Of Duty Black Ops 3 " ,
        company:'',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:792,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_BO3.jpg',
        price:123.78,
        like:false ,
    },
    {//36
        id:"35C" ,
        name:"Call Of Duty Modern Warfare" ,
        company:'Treyarch',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:121 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_MW.jpg',
        price:37.99,
        like:true ,
    },
    {//37
        id:"36C" ,
        name:"Call Of Duty Modern Warfare 2" ,
        company:'Sledgehammer Games',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:220 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_MW2.jpg',
        price:51,
        like:false ,
    },
    {//38
        id:"37C" ,
        name:"Call Of Duty War Zone" ,
        company:'Raven Software',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:499,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_WZ.jpg',
        price:80,
        like:true ,
    },
    {//39
        id:"38C" ,
        name:"Call Of Duty 1 WWII" ,
        company:'Infinity Ward',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:300 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD1_WWII.jpg',
        price:17.1,
        like:true ,
    },
    {//40
        id:"39C" ,
        name:"Call Of Duty 2 WWII" ,
        company:'Infinity Ward',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:684 ,
        genres:[ "Shooting" , "Action" , "Survival" , "Multiplayer"] ,
        image : '../FakeData/MainImages/COD2_WWII.jpg',
        price:24.8,
        like:false ,
    },
    {//41
        id:"40P" ,
        name:"PES 2021" ,
        company:'Konami',
        type:"3D",
        platforms:[ "Windows" , "PES" , "Xbox" ] ,
        stock:147 ,
        genres:[ "Sport"  , "Strategy" , "Multiplayer"] ,
        image : '../FakeData/MainImages/Pes2021.jpg',
        price:47.83,
        like:true ,
    },
    {//42
        id:"41P" ,
        name:"Pasteur" ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Windows" , "MacOs","Linux"] ,
        stock:978 ,
        genres:[ "Card"] ,
        image : '../FakeData/MainImages/Pasteur.jpg',
        price:2.14,
        like:false ,
    },
    {//43
        id:"42P" ,
        name:"Pacman" ,
        company:'Namco',
        type:"2D",
        platforms:[ "Windows" , "MacOs","Linux" ] ,
        stock:195 ,
        genres:[ "Puzzle" , "Survival"] ,
        image : '../FakeData/MainImages/Pacman.jpg',
        price:1.7,
        like:true ,
    },
    {//44
        id:"43P" ,
        name:"Packet Tanks" ,
        company:'Blitwise Productions',
        type:"2D",
        platforms:[ "Windows" , "MacOs" ] ,
        stock:76 ,
        genres:[ "Puzzle" , "Survival" , "MultiPlayer"] ,
        image : '../FakeData/MainImages/PacketTanks.jpg',
        price:8.9,
        like:false ,
    },
    {//45
        id:"44N" ,
        name:"Neighbor Of Hell" ,
        company:'Big Moon Entertainment',
        type:"2D",
        platforms:[ "Windows" , "MacOs" ,"Linux"] ,
        stock:500 ,
        genres:[ "Puzzle" ] ,
        image : '../FakeData/MainImages/NeighborOfHell.jpg',
        price:11.5,
        like:false ,
    },
    {//46
        id:"45N" ,
        name:"Need For Speed" ,
        company:'Criterion Games',
        type:"3D",
        platforms:[ "Windows" , "Ps" , "Xbox" ] ,
        stock:247 ,
        genres:[ "Sport" , "Racing" , ] ,
        image : '../FakeData/MainImages/NeedForSpeed.jpg',
        price:49.99,
        like:true ,
    },
    {//47
        id:"46M" ,
        name:"Mortal Kombat 3D" ,
        company:'Midway Games',
        type:"3D",
        platforms:[ "Windows" , "Ps" , "Xbox" ] ,
        stock:777 ,
        genres:[ "Fighting" , "Multiplayer" , "Survival"] ,
        image : '../FakeData/MainImages/MortalCombat3D.jpg',
        price:23,
        like:false ,
    },
    {//48
        id:"47M" ,
        name:"Mortal Kombat 2D" ,
        company:'Midway Games',
        type:"2D",
        platforms:[ "Windows" , "Ps" , "Xbox" ] ,
        stock:148 ,
        genres:[ "Fighting" , "Multiplayer" , "Survival"] ,
        image : '../FakeData/MainImages/MortalCombat2D.jpg',
        price:10,
        like:false ,
    },
    {//49
        id:"48M" ,
        name:"Mini Soldiers" ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Ps"  ] ,
        stock:93 ,
        genres:[ "Fighting" , "Multiplayer"] ,
        image : '../FakeData/MainImages/MiniSoldiers.jpg',
        price:3.25,
        like:false ,
    },
    {//50
        id:"49I" ,
        name:"IGI 2" ,
        company:'Innerloop Studios',
        type:"3D",
        platforms:["Windows" ] ,
        stock:39 ,
        genres:[ "Shooting" ] ,
        image : '../FakeData/MainImages/Igi2.jpg',
        price:11.1,
        like:true ,
    },
    {//51
        id:"50I" ,
        name:"IGI 1" ,
        company:'Innerloop Studios',
        type:"3D",
        platforms:["Windows" ] ,
        stock:299 ,
        genres:[ "Shooting" ] ,
        image : '../FakeData/MainImages/Igi1.jpg',
        price:6.2,
        like:false ,
    },
    {//52
        id:"51I" ,
        name:"Ice Of Age" ,
        company:'Unknow',
        type:"3D",
        platforms:["Windows" , "Ps" , "Xbox" ] ,
        stock:800 ,
        genres:["Adventure" ] ,
        image : '../FakeData/MainImages/IceOfAge.jpg',
        price:19.99,
        like:false ,
    },
    {//53
        id:"52C" ,
        name:"Counter Strike Cs Go" ,
        company:'Valve Corporation',
        type:"3D",
        platforms:["Windows" , "Ps"  ] ,
        stock:930 ,
        genres:[ "Shooter" , "Action" ] ,
        image : '../FakeData/MainImages/CounterStrikeCsGo.jpg',
        price:7.77,
        like:true ,
    },
    {//54
        id:"53C" ,
        name:"Counter Strike Global" ,
        company:'Valve Corporation',
        type:"3D",
        platforms:["Windows" , "Ps"  ] ,
        stock:583 ,
        genres:[ "Shooter" , "Action" ] ,
        image : '../FakeData/MainImages/CounterStrikeGlobal.jpg',
        price:5.50,
        like:false ,
    },
    {//55
        id:"54D" ,
        name:"Dota 2" ,
        company:'Valve Corporation',
        type:"3D",
        platforms:["Windows" , "Linux" ] ,
        stock:12 ,
        genres:[ "Strategy"  ] ,
        image : '../FakeData/MainImages/Dota2.jpg',
        price:0,
        like:true ,
    },
    {//56
        id:"55F" ,
        name:"Farlight" ,
        company:'Lilith Games',
        type:"3D",
        platforms:["Windows" , "Linux" , "Xbox" , "Ps"] ,
        stock:999 ,
        genres:[ "Battleroyal"  ] ,
        image : '../FakeData/MainImages/Farlight.jpg',
        price:15,
        like:false ,
    },
    {//57
        id:"56F" ,
        name:"FiFa 2021" ,
        company:'EA Games',
        type:"3D",
        platforms:["Windows"  , "Xbox" , "Ps"] ,
        stock:181 ,
        genres:[ "Sport"  ] ,
        image : '../FakeData/MainImages/FiFa2021.jpg',
        price:20,
        like:false ,
    },
    {//58
        id:"57F" ,
        name:"FiFa 2022" ,
        company:'EA Games',
        type:"3D",
        platforms:["Windows"  , "Xbox" , "Ps"] ,
        stock:337 ,
        genres:[ "Sport"  ] ,
        image : '../FakeData/MainImages/FiFa2022.jpg',
        price:29.99,
        like:false ,
    },
    {//59
        id:"58F" ,
        name:"FiFa 2023" ,
        company:'EA Games',
        type:"3D",
        platforms:["Windows"  , "Xbox" , "Ps"] ,
        stock:502 ,
        genres:[ "Sport"  ] ,
        image : '../FakeData/MainImages/FiFa2023.jpg',
        price:36.5,
        like:false ,
    },
    {//60
        id:"59F" ,
        name:"Free fire" ,
        company:'Garena',
        type:"3D",
        platforms:["Windows"  , "Xbox" , "Ps" , "Android"] ,
        stock:1000 ,
        genres:[ "Battleroyal" , "Shooting" , "Survival"  ] ,
        image : '../FakeData/MainImages/FreeFire.jpg',
        price:0.66,
        like:false ,
    },
    {//61
        id:"60F" ,
        name:"Fruit Ninja" ,
        company:'Halfbrick Studios',
        type:"2D",
        platforms:[ "Android" , "Ios"] ,
        stock:100 ,
        genres:[ "Puzzle" , "Fighting"] ,
        image : '../FakeData/MainImages/FruitNinja.jpg',
        price:1.4,
        like:false ,
    },
    {//62
        id:"61G" ,
        name:"Generals 1" ,
        company:'EA Games',
        type:"3D",
        platforms:["Windows" ] ,
        stock:449 ,
        genres:[ "Strategy" , "Survival"] ,
        image : '../FakeData/MainImages/GeneralCapture1.jpg',
        price:18.88,
        like:true ,
    },
    {//63
        id:"62G" ,
        name:"Generals 2" ,
        company:'EA Games',
        type:"3D",
        platforms:["Windows" ] ,
        stock:571 ,
        genres:[ "Strategy" , "Survival"] ,
        image : '../FakeData/MainImages/GeneralCapture2.jpg',
        price:22.22,
        like:true ,
    },
    {//64
        id:"63G" ,
        name:"Go Battle" ,
        company:'Unknow',
        type:"2D",
        platforms:[ "Ps" , "Xbox" ] ,
        stock:0 ,
        genres:[ "Fighting"] ,
        image : '../FakeData/MainImages/GoBattle.jpg',
        price:0.1,
        like:false ,
    },
    {//65
        id:"64G" ,
        name:"God Of War 2" ,
        company:'Santa Monica Studio',
        type:"3D",
        platforms:[ "Ps" , "Xbox" ] ,
        stock:750 ,
        genres:[ "Fighting" , "Adventure"] ,
        image : '../FakeData/MainImages/GodOfWarCaptue2.jpg',
        price:9.99,
        like:true ,
    },
    {//66
        id:"65G" ,
        name:"God Of War 3" ,
        company:'Santa Monica Studio',
        type:"3D",
        platforms:[ "Ps" , "Xbox" ] ,
        stock:803 ,
        genres:[ "Fighting" , "Adventure"] ,
        image : '../FakeData/MainImages/GodOfWarCaptue3.jpg',
        price:13.4,
        like:false ,
    },
    {//67
        id:"66G" ,
        name:"God Of War 4" ,
        company:'Santa Monica Studio',
        type:"3D",
        platforms:[ "Ps" , "Xbox" ] ,
        stock:617 ,
        genres:[ "Fighting" , "Adventure"] ,
        image : '../FakeData/MainImages/GodOfWarCaptue4.jpg',
        price:30,
        like:false ,
    },
    {//68
        id:"67G" ,
        name:"Gta IV" ,
        company:'Rockstar Games',
        type:"3D",
        platforms:[ "Windows","Ps" , "Xbox" ] ,
        stock:268 ,
        genres:[ "Fighting" , "Adventure" ,"Shooting"] ,
        image : '../FakeData/MainImages/GtaIv.jpg',
        price:45,
        like:false ,
    },
    {//69
        id:"68G" ,
        name:"Gta San" ,
        company:'Rockstar Games',
        type:"3D",
        platforms:[ "Windows","Ps" , "Xbox" ] ,
        stock:390 ,
        genres:[ "Fighting" , "Adventure" ,"Shooting"] ,
        image : '../FakeData/MainImages/GtaSan.jpg',
        price:12,
        like:false ,
    },
    {//70
        id:"69G" ,
        name:"Gta V" ,
        company:'Rockstar Games',
        type:"3D",
        platforms:[ "Windows","Ps" , "Xbox" ] ,
        stock:785 ,
        genres:[ "Fighting" , "Adventure" ,"Shooting"] ,
        image : '../FakeData/MainImages/GtaV.jpg',
        price:60,
        like:true ,
    },



]
export function getAllGames() {
    return AllGames;
}
export function get2DGames() {
    return AllGames.filter(game => game.type.trim() === "2D");
}
export function get3DGames() {
    return AllGames.filter(game => game.type.trim() === "3D");
}